language: node_js
node_js:
    - "4"
    - "6"

os:
    - osx

cache:
    directories:
        - node_modules

matrix:
    fast_finish: true

before_install:
    - npm install -g npm@latest

install:
    - npm install

script:
    - npm run test-ci