language: node_js
node_js:
    - "4"
    - "6"

cache:
    directories:
        - node_modules

matrix:
    fast_finish: true

before_install:
    - npm install -g npm@latest

script:
    - npm run test-ci